### ISSUE TITLE
Feature Discussion: A public "reflection" or "introspection" API

### ISSUE THREAD

**Issue by srishanbhattarai** [kabirbaidhya/boss#123]
I'm opening this issue with the aim of it being more of a discussion than a Yes/No answer. Maybe you already have certain plans in place for this 😄 

What do you think about Boss having a public facing "reflection" or "introspection" API - a way for external tools to communicate with Boss to introspect deployment targets. It would answer questions like:
  - What's the latest git commit SHA?
  - What's the last deployment timestamp for branch master? etc.

For instance, a service could create reports based on this information (perhaps visualize it in GUI). A service could reconcile branches deployed with project management board tickets (e.g JIRA) to know what ticket's been deployed where. In general it would really useful for building things on top of what Boss already provides, possibly in other languages.

The technicalities of communication method, protocol etc. would be another point of discussion if you are interested in this!

**Comment by kabirbaidhya** [comment]
@srishanbhattarai Great. Thanks for creating the issue. 

Yes, I had already thought of this but haven't even got time to work on even the basic POC.
This repository is only about the CLI for boss, so it's out of scope for it to have an API exposing these information.

What this CLI does is an offer a client facing interface to let the user do remote execution (over paramiko/fabric) and deployment over SSH to remote host. Now since these information like git commit SHA has, last deployment timestamp, who deployed what, deployment history, current hash etc are something specific to each different environments where the code is deployed, we'll need a separate service which can expose these data over a public endpoint.

What I've in mind is to have a [dashboard](https://github.com/kabirbaidhya/boss-dashboard) that includes both the API and UI (possibly be next + micro or something) that could both work as persistence layer and a public API exposing all the deployment information.  But, I had not thought of the interoperability with other external services yet so thanks for suggesting that!

As of now, boss uses a flat json file to store all these information which read/written over SSH. There's no way any external service over HTTP could access it right now until we build a public endpoint, so the purpose of the dashboard is to have that. Furthermore, if this API is built this could be used both as a persistance layer and an API offering interoperability for other services to integrate - because we no longer have to rely on just a flat json file over SSH like now, we can have a POST request over HTTPS to persist it.

Let me know if you're interested in contribution or have any suggestion.

**Comment by srishanbhattarai** [comment]
The dashboard sounds good! 

I was actually thinking of something really basic to get started - along with the `builds.json` file that we have to store information, we could have, for example, a `metadata.json` file that could introspect the environment under which it is run and store whatever information it can. The third party tools could then just ask the CLI about information contained in the `metadata.json` file. Even interacting directly through the CLI for a start (no webhooks or anything) could enable different tools, which may help decide if something like this is even worth the effort?

I'd be happy to contribute! 😄
